c_compiler:                    # [win or linux]
- vs2019                       # [win]
- gcc =10.*                    # [linux]
cxx_compiler:                  # [win or linux]
- vs2019                       # [win]
- gxx =10.*                    # [linux]
