# NOTE: pin clang to version 16 on OSX x86_64
# for the time being, due to what looks like a clang-19 bug.
c_compiler_version:        # [osx and x86_64]
  - 18                     # [osx and x86_64]
cxx_compiler_version:      # [osx and x86_64]
  - 18                     # [osx and x86_64]
