{% set name = "heyoka.py" %}
{% set version = "5.0.0" %}
{% set sha256 = "b0759366eba2b733958a3d22c92ebf79e76bf663366e1a3220ab08b4ebf98114" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bluescarni/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy <2                               # [build_platform != target_platform]
    - pybind11 >=2.10                        # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make       # [unix]
    - ninja      # [unix]
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    # NOTE: at this time, both heyoka and heyoka.py
    # are rapidly evolving with frequent API changes,
    # thus it is better to keep the versions explicitly
    # in sync for now.
    - heyoka-llvm-18 =5.*
    - libboost-devel >=1.69
    - tbb-devel
    - fmt >=9,<11
    - numpy <2
    - mppp =1.*
    - gmp   # [unix]
    - mpir  # [win]
    - mpfr
  run:
    - python
    - mpmath
    - sympy
    - cloudpickle

about:
  home: https://bluescarni.github.io/heyoka.py/
  license: MPL-2.0
  license_file: LICENSE
  summary: Python library for ODE integration via Taylor's method and LLVM

extra:
  recipe-maintainers:
    - bluescarni
