{% set name = "heyoka.py" %}
{% set version = "0.15.1" %}
{% set sha256 = "53a17eda7d4f284dda976c9930341a9ba5b96b4c0122e03038c6ff1f2a96e6fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bluescarni/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - win_fix.diff

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make       # [unix]
  host:
    - python
    - pybind11
    - pybind11-abi
    # NOTE: at this time, both heyoka and heyoka.py
    # are rapidly evolving with frequent API changes,
    # thus it is better to keep the versions explicitly
    # in sync for now.
    - heyoka >=0.15.0
    - boost-cpp
    - fmt
    - spdlog
    - numpy
    - mppp  # [linux and (x86 or ppc64le)]
    - gmp   # [linux and (x86 or ppc64le)]
    - mpfr  # [linux and (x86 or ppc64le)]
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - python
    - mpmath  # [linux and (x86 or ppc64le)]
    - sympy
    - cloudpickle

about:
  home: https://bluescarni.github.io/heyoka.py/
  license: MPL-2.0
  license_file: LICENSE
  summary: Python library for ODE integration via Taylor's method and LLVM

extra:
  recipe-maintainers:
    - bluescarni
