{% set name = "heyoka.py" %}
{% set version = "7.0.0" %}
{% set sha256 = "51b6a75aaa96d31e9cfbe04d011bb260cefcf9e50e80130a1265c696a6f49c0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bluescarni/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy =2.*                             # [build_platform != target_platform]
    - pybind11 >=2.10                        # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make       # [unix]
    - ninja      # [unix]
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    # NOTE: at this time, both heyoka and heyoka.py
    # are rapidly evolving with frequent API changes,
    # thus it is better to keep the versions explicitly
    # in sync for now.
    - heyoka-llvm-19 =7.0.*
    - libboost-devel
    - tbb-devel
    - fmt
    - numpy =2.*
    - mppp =2.*
    - gmp
    - mpfr
  run:
    - numpy =2.*
    - python
    - mpmath
    # NOTE: the way SymPy deals with floating-point numbers
    # has slightly changed in 1.13.0, which required changes
    # in heyoka as well.
    - sympy >=1.13.0
    - cloudpickle

about:
  home: https://bluescarni.github.io/heyoka.py/
  license: MPL-2.0
  license_file: LICENSE
  summary: Python library for ODE integration via Taylor's method and LLVM

extra:
  recipe-maintainers:
    - bluescarni
