{% set name = "heyoka.py" %}
{% set version = "0.7.0" %}
{% set sha256 = "d80b94a36fa66c5e2d90d378dd1c0df7390ab86eaefafa353c52de8968add4f0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bluescarni/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake <3.20
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - clang      # [win]
    - ninja      # [win]
  host:
    - python
    - pybind11
    - pybind11-abi
    - heyoka
    - boost-cpp
    - fmt
    - spdlog
    - numpy
    - mppp  # [linux]
    - gmp   # [linux]
    - mpfr  # [linux]
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - mpmath  # [linux]

about:
  home: https://bluescarni.github.io/heyoka.py/
  license: MPL-2.0
  license_file: LICENSE
  summary: Python library for ODE integration via Taylor's method and LLVM

extra:
  recipe-maintainers:
    - bluescarni
