{% set name = "heyoka.py" %}
{% set version = "0.10.0" %}
{% set sha256 = "ee48ad7bd8637c1b2a83b8ed6b522a2acd7fd4cc5425cbd51eaba9383fbc9012" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bluescarni/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - cmake <3.20
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - clang      # [win]
    - ninja      # [win]
  host:
    - python
    - pybind11
    - pybind11-abi
    # NOTE: at this time, both heyoka and heyoka.py
    # are rapidly evolving with frequent API changes,
    # thus it is better to keep the versions explicitly
    # in sync for now.
    - heyoka >=0.10.0
    - boost-cpp
    - fmt
    - spdlog
    - numpy
    - mppp  # [linux]
    - gmp   # [linux]
    - mpfr  # [linux]
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - mpmath  # [linux]
    - sympy

about:
  home: https://bluescarni.github.io/heyoka.py/
  license: MPL-2.0
  license_file: LICENSE
  summary: Python library for ODE integration via Taylor's method and LLVM

extra:
  recipe-maintainers:
    - bluescarni
