{% set name = "heyoka.py" %}
{% set version = "3.0.0" %}
{% set sha256 = "09e7f3b91188070c8c5731142762394b97b51d83571e17c190b2c855e9ea263d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bluescarni/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.22                           # [build_platform != target_platform]
    - pybind11 >=2.10                        # [build_platform != target_platform]
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make       # [unix]
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    # NOTE: at this time, both heyoka and heyoka.py
    # are rapidly evolving with frequent API changes,
    # thus it is better to keep the versions explicitly
    # in sync for now.
    - heyoka-llvm-16 =2.0.*
    - libboost-devel
    - tbb-devel
    - fmt
    - numpy >=1.22
    - mppp >=0.27
    - gmp   # [unix]
    - mpir  # [win]
    - mpfr
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - mpmath
    - sympy
    - cloudpickle

about:
  home: https://bluescarni.github.io/heyoka.py/
  license: MPL-2.0
  license_file: LICENSE
  summary: Python library for ODE integration via Taylor's method and LLVM

extra:
  recipe-maintainers:
    - bluescarni
