{% set name = "heyoka.py" %}
{% set version = "0.17.0" %}
{% set sha256 = "4765162bef944c7365ebbb69fe580cf76e65a5744e1a4bb657b84cd396a6f3c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bluescarni/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make       # [unix]
  host:
    - python
    - pybind11
    - pybind11-abi
    # NOTE: at this time, both heyoka and heyoka.py
    # are rapidly evolving with frequent API changes,
    # thus it is better to keep the versions explicitly
    # in sync for now.
    - heyoka-llvm-13 >=0.17.1
    - boost-cpp
    # NOTE: pin fmt/spdlog versions
    # so that there is only one version of fmt.
    - fmt =8.0.*
    - spdlog =1.9.2
    - numpy
    - mppp  # [linux and (x86 or ppc64le)]
    - gmp   # [linux and (x86 or ppc64le)]
    - mpfr  # [linux and (x86 or ppc64le)]
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - python
    - mpmath  # [linux and (x86 or ppc64le)]
    - sympy
    - cloudpickle

about:
  home: https://bluescarni.github.io/heyoka.py/
  license: MPL-2.0
  license_file: LICENSE
  summary: Python library for ODE integration via Taylor's method and LLVM

extra:
  recipe-maintainers:
    - bluescarni
